# Generated by Django 4.2

# The model was removed but the migration wasn't squashed properly
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidateskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_locations', models.JSONField(default=list)),
                ('min_salary', models.PositiveIntegerField(null=True, blank=True)),
                ('max_commute_minutes', models.PositiveIntegerField(null=True, blank=True)),
                ('remote_only', models.BooleanField(default=False)),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='candidates.candidate')),
            ],
            options={
                'db_table': 'candidates_candidate_preference',
            },
        ),
    ]
