# Generated by Django 4.2
# This migration deletes the CandidatePreference model
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidatepreference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidatePreference',
        ),
    ]
