# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.2.2'

gem 'rails', '~> 7.1.0'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.4'
gem 'redis', '~> 5.0'
gem 'sidekiq', '~> 7.2'
gem 'ruby-kafka', '~> 1.5'
gem 'aasm', '~> 5.5'
gem 'jbuilder', '~> 2.11'
gem 'bootsnap', require: false

# Authentication
gem 'jwt', '~> 2.7'

# Serialization
gem 'active_model_serializers', '~> 0.10'

# Monitoring
gem 'sentry-ruby'
gem 'sentry-rails'

group :development, :test do
  gem 'rspec-rails', '~> 6.1'
  gem 'factory_bot_rails', '~> 6.4'
  gem 'faker', '~> 3.2'
  gem 'pry-rails'
  gem 'bullet'
end

group :test do
  gem 'shoulda-matchers', '~> 5.3'
  gem 'database_cleaner-active_record'
  gem 'webmock', '~> 3.19'
  gem 'timecop', '~> 0.9'
end
