source 'https://rubygems.org'

ruby '3.2.2'

# Rails
gem 'rails', '~> 7.1.2'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.4'

# Authentication & Authorization
gem 'devise', '~> 4.9'
gem 'pundit', '~> 2.3'
gem 'jwt', '~> 2.7'

# Background Jobs
gem 'sidekiq', '~> 7.2'
gem 'sidekiq-scheduler', '~> 5.0'

# Caching & Performance
gem 'redis', '~> 5.0'
gem 'connection_pool', '~> 2.4'
gem 'bootsnap', require: false

# API
gem 'jbuilder', '~> 2.11'
gem 'rack-cors', '~> 2.0'

# File uploads
gem 'activestorage', '~> 7.1'
gem 'aws-sdk-s3', '~> 1.141'

# Monitoring
gem 'sentry-ruby', '~> 5.15'
gem 'sentry-rails', '~> 5.15'

# Utilities
gem 'friendly_id', '~> 5.5'
gem 'aasm', '~> 5.5'
gem 'paper_trail', '~> 15.1'

group :development, :test do
  gem 'rspec-rails', '~> 6.1'
  gem 'factory_bot_rails', '~> 6.4'
  gem 'faker', '~> 3.2'
  gem 'pry-rails', '~> 0.3'
  gem 'debug', '~> 1.9'
end

group :test do
  gem 'shoulda-matchers', '~> 5.3'
  gem 'database_cleaner-active_record', '~> 2.1'
  gem 'webmock', '~> 3.19'
  gem 'vcr', '~> 6.2'
  gem 'simplecov', '~> 0.22', require: false
  gem 'timecop', '~> 0.9'
end

group :development do
  gem 'rubocop', '~> 1.59', require: false
  gem 'rubocop-rails', '~> 2.23', require: false
  gem 'rubocop-rspec', '~> 2.25', require: false
  gem 'brakeman', '~> 6.1', require: false
end
